language: node_js
node_js:
- '10'
cache: npm
install:
- npm ci
branches:
  only:
  - master
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "CjAinwAp1SdlatzgvVQtxn4ALYQGCCC4C0Zq3QjJzuhVpEDrLHrNzxT0thAq2BLjnRlFPb312eKG/7Hh2XggTXPgPmjcvltdZFfgCwF5/S6zyk/YFCY41vLNqeIl+ChwwFfyyszyvAb4yloflLH4gJ07euk1povv+9CpQdyBd0XuWcEsdonajU6G5DR+nUteJESI1WV1uCj14GUFiHFcuGiIeaNHvhYZjWulXGvBIAo9GPg3QbffArlUtqq19bWFa4kyl/EF2WiwaFR4UDkI4PonhZSSkI73Ufsy7n+IfMTZqlQLl30nab01YaIqgB+GEvCU3tVUU3XI0fTN2KMbYP2wcwuS9XBVgE6pEEQv6RgWz4oI9V5HhfSkXt9RUubqnn0WZhRofIuJASAu1r8XblC4+P8G9As3qncHSDw8XpVU45pnzg0Iq05rUSldlfKWfAsz5ayno/SaYi6cw9iZReCjD/XwipCuueb11DUgmKwSmL6MnS/aMFPJ4MAt7pTjKfrVj48b+/9ie+N2KUciRvyO/2c3FN6vUkt+a9GbQXHk5Q9sfoAzeSWkr4EhpqUnKxTgFYCvlrSuMHaCjFwweQ3ioeJSQaTRGplsD2a/9Aurp6x9/MoTkLVHlEDr0hobS3UUK44XRTkHLYIWkTyiiqKSdpDHHECsQlS99LnFUTw="
  project: larissavarjao-8