language: node_js
node_js:
- '10'
cache: npm
install:
- npm ci
branches:
  only:
  - master
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: Na4+48hGu7Csg8WyKPEpARfLZ15VNYLBFSEp84DfPfUPJntL9bNC81ZXjbeKYRtdhOYFMQhQ83MivBM1Y6OWLN/TXTS/4UMYcSnXBJhHD8MeBTGwaS2wFSaB9Uz1y7ba7FSkq45iCsMvGWDxmcZF/JPOMovCusvpkuMN5rq4BEKFeI2G4QS6HHRZrbp3OVlZABsBJPOwIyQH55Q/4y7ATHTPoVLKe9pyngUweEXcbbglwaYED80/oo1oUwx5EWCNgS+obz8oRTivaoZwgmCCobZda1Ch8iGEVmvOkncNAF42R7s8Qm79B84aqhdU2QZFLPqVsGjgD9WEyXe3lZW5vPCSyg288eDA0q7XUypRISqz//8UdhdvBWyIK560h40mJQT+ISF78Q7e12O23Y3Hbhs4QxX4edSW0AQQnscJE0LEUBZ8XmYF3HZqEqviwLNkVaXAGUqCMmcJxFupRQd3mJhURSd0zM4B7D6jKsR/xEzsR8pmnOp2VOJkrZgLmabxxQsqQHoNZRThVMi9CSfC2YTaOXKKp4Fcyqj6VAhLCs1jsxie80AW54NOO++X09AiHNA7kE1TfuzF+JhlHTJm2BFMTlsf8dAKXhY5Oi2tzZXFb0oZrYe6kRE+lj3IQIhkoXknzMaCAN0m+8E6g+ZeKad/fRFOYSuixty0w33I5Uw=
  project: larissavarjao-8
env:
  global:
    secure: PeaAw9P5YWUK2eBJH+sEGCdn6Kuc7vgXNZLWicta5PyvmYrSbay5d7Ae/WF0WmSKeYSD5YL5hJB5Z2cQXYUFJKL6NS9sAjzlWe8y/tiUAO9QWRPpD/fVzljtmOnfAhk+vAho8Rny5Y/JQNu3GcIqUqY1gqX5Hd0m5nhlofa8IeDm9bZo+Q3TdxrcoNCCV1mp2zd1qKPhtJ5xwI13mrrfIgbQilXoDWX44xDIXyu+sLsvZ5PF1EQE4xRtI9+/ummXVLWiKJ/Ik7E+pOApdbLRGYshuqqYmP4NJSiGrmzjFvm+wzEwOeaRtNytyoftkF6CD5xfBJoMqFN6x9XwyT/taWFuii7RzZ7BjoN2P9bv0H8U1HA/28S46Y/ubkNvkVdQVJWjDJJpDRS0xdQD/WbYdYDISJonuRxY4ql6QoQAFnEuLyyVTngA+B0Rv8wmmdJNwXk9TS+fP6BjJQ63PN63qUK9Y+F64WDBxxj4+Hc7enHJ/7147Y/UMY8f5j4GBq+lj80ZqEP/2bkWiRXOyH9jPN8BcJ5VCFvlqzMVzl/8jgLAI5WRjSmkZceT8qYOAzglxvagxA+eT+zoWkc6EAJnyPttDl0atvQcz4EYLlAB7vUl/gmRaFbkliJEDwdAMQDqFCzWuAu2QtJD9ReAtkI8SJWcaKZSwMqdp+MeIhU+s6o=
