language: node_js
node_js:
  - "10"
cache: npm
install:
  - npm ci
branches:
  only:
    - master
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: Na4+48hGu7Csg8WyKPEpARfLZ15VNYLBFSEp84DfPfUPJntL9bNC81ZXjbeKYRtdhOYFMQhQ83MivBM1Y6OWLN/TXTS/4UMYcSnXBJhHD8MeBTGwaS2wFSaB9Uz1y7ba7FSkq45iCsMvGWDxmcZF/JPOMovCusvpkuMN5rq4BEKFeI2G4QS6HHRZrbp3OVlZABsBJPOwIyQH55Q/4y7ATHTPoVLKe9pyngUweEXcbbglwaYED80/oo1oUwx5EWCNgS+obz8oRTivaoZwgmCCobZda1Ch8iGEVmvOkncNAF42R7s8Qm79B84aqhdU2QZFLPqVsGjgD9WEyXe3lZW5vPCSyg288eDA0q7XUypRISqz//8UdhdvBWyIK560h40mJQT+ISF78Q7e12O23Y3Hbhs4QxX4edSW0AQQnscJE0LEUBZ8XmYF3HZqEqviwLNkVaXAGUqCMmcJxFupRQd3mJhURSd0zM4B7D6jKsR/xEzsR8pmnOp2VOJkrZgLmabxxQsqQHoNZRThVMi9CSfC2YTaOXKKp4Fcyqj6VAhLCs1jsxie80AW54NOO++X09AiHNA7kE1TfuzF+JhlHTJm2BFMTlsf8dAKXhY5Oi2tzZXFb0oZrYe6kRE+lj3IQIhkoXknzMaCAN0m+8E6g+ZeKad/fRFOYSuixty0w33I5Uw=
  project: larissavarjao-8
