language: node_js
node_js:
  - "10"
cache: npm
install:
  - npm ci
branches:
  only:
    - master
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: s6YAtEKwXl+TlrRx6lsZC+B+Dg2kRpbQNXFigKGgXyIE2O7MrohRIk3qjzYdgoIgpnxHgJdGLTRyHZjD5IlMPyxb0+ZuCtigEOKQ0alnaP+WOL+tu8yLYHC6AwzKm9QICSdMHbrwW25ajVt99lB3+fImLO1GwXdQ+SasdtcYbO48cSGeUrkGFqO73U33vYkF5CzC73aPlf1kA4RTcsjd6ho2txp8Il7m51GLVD+CBWjd/6U2xbFcdhQYrgx79SPSHNyb9R0T9HBg9oRY8hhfL7JYzRPaRQA+Kcmm6o2lecyEkL6tQ9QzK4sszzYgHwzErJBfx4sIkLg/hi5qirV+5uJ8Ul43QOP1xTHAiYtaD35xpnGHANaBk1bxrGzXfosTv7S4uIxoXPP4kad3mfipSbRRSVQ5hq+hG2wH2cROi9t98hFMMXZTlANEzqeMz9Wd/nA9ey+eRDZ5UuuBJVL7/ZymOZEkA66ohQHqdb/9kf30057MOoF9OZkGWMV21fq35CFoEiJdpqStenyCyxsTGpgcezzDf0iuNw58l0kf0D4lZyIsaByR4O57KYm47ZyDehqMOKexNtMu7s7uN4TagALKbIrCcPcxGUZrMzX+5JfkKlNKcwXXYxPBL3u39TbN6uKcF50F3EaMLYOG587KrQ+kMpF/QibllYsdRxtP+FQ=
  project: larissavarjao-8
