language: node_js
node_js:
- '10'
cache: npm
install:
- npm ci
branches:
  only:
  - master
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: PeaAw9P5YWUK2eBJH+sEGCdn6Kuc7vgXNZLWicta5PyvmYrSbay5d7Ae/WF0WmSKeYSD5YL5hJB5Z2cQXYUFJKL6NS9sAjzlWe8y/tiUAO9QWRPpD/fVzljtmOnfAhk+vAho8Rny5Y/JQNu3GcIqUqY1gqX5Hd0m5nhlofa8IeDm9bZo+Q3TdxrcoNCCV1mp2zd1qKPhtJ5xwI13mrrfIgbQilXoDWX44xDIXyu+sLsvZ5PF1EQE4xRtI9+/ummXVLWiKJ/Ik7E+pOApdbLRGYshuqqYmP4NJSiGrmzjFvm+wzEwOeaRtNytyoftkF6CD5xfBJoMqFN6x9XwyT/taWFuii7RzZ7BjoN2P9bv0H8U1HA/28S46Y/ubkNvkVdQVJWjDJJpDRS0xdQD/WbYdYDISJonuRxY4ql6QoQAFnEuLyyVTngA+B0Rv8wmmdJNwXk9TS+fP6BjJQ63PN63qUK9Y+F64WDBxxj4+Hc7enHJ/7147Y/UMY8f5j4GBq+lj80ZqEP/2bkWiRXOyH9jPN8BcJ5VCFvlqzMVzl/8jgLAI5WRjSmkZceT8qYOAzglxvagxA+eT+zoWkc6EAJnyPttDl0atvQcz4EYLlAB7vUl/gmRaFbkliJEDwdAMQDqFCzWuAu2QtJD9ReAtkI8SJWcaKZSwMqdp+MeIhU+s6o=
  project: larissavarjao-8
env:
  global:
    secure: PeaAw9P5YWUK2eBJH+sEGCdn6Kuc7vgXNZLWicta5PyvmYrSbay5d7Ae/WF0WmSKeYSD5YL5hJB5Z2cQXYUFJKL6NS9sAjzlWe8y/tiUAO9QWRPpD/fVzljtmOnfAhk+vAho8Rny5Y/JQNu3GcIqUqY1gqX5Hd0m5nhlofa8IeDm9bZo+Q3TdxrcoNCCV1mp2zd1qKPhtJ5xwI13mrrfIgbQilXoDWX44xDIXyu+sLsvZ5PF1EQE4xRtI9+/ummXVLWiKJ/Ik7E+pOApdbLRGYshuqqYmP4NJSiGrmzjFvm+wzEwOeaRtNytyoftkF6CD5xfBJoMqFN6x9XwyT/taWFuii7RzZ7BjoN2P9bv0H8U1HA/28S46Y/ubkNvkVdQVJWjDJJpDRS0xdQD/WbYdYDISJonuRxY4ql6QoQAFnEuLyyVTngA+B0Rv8wmmdJNwXk9TS+fP6BjJQ63PN63qUK9Y+F64WDBxxj4+Hc7enHJ/7147Y/UMY8f5j4GBq+lj80ZqEP/2bkWiRXOyH9jPN8BcJ5VCFvlqzMVzl/8jgLAI5WRjSmkZceT8qYOAzglxvagxA+eT+zoWkc6EAJnyPttDl0atvQcz4EYLlAB7vUl/gmRaFbkliJEDwdAMQDqFCzWuAu2QtJD9ReAtkI8SJWcaKZSwMqdp+MeIhU+s6o=
